Upgrade ./dk

diff --git a/dk b/dk
--- a/dk
+++ b/dk
@@ -479,17 +479,22 @@ PROJ_DIR=$(dirname "$0")
 PROJ_DIR=$(cd "$PROJ_DIR" && pwd)
 cd "$PROJ_DIR"
 
-# --- Tool directory selection ---
+# --- DkCoder data home ---
 
 tools_dir=
 tools_name=dkcoder
-#   1. Check if CI since many CI providers can only cache content in a subdirectory
+#   1. Check DKCODER_DATA_HOME environment variable.
+if [ -z "$tools_dir" ] && [ -n "${DKCODER_DATA_HOME:-}" ]; then
+  install -d "$DKCODER_DATA_HOME"
+  tools_dir="$DKCODER_DATA_HOME"
+fi
+#   2. Check if CI since many CI providers can only cache content in a subdirectory
 #      of the project.
 if [ -z "$tools_dir" ] && [ "${CI:-}" = true ]; then
-  install -d "$PROJ_DIR/.tools"
-  tools_dir="$PROJ_DIR/.tools"
+  install -d "$PROJ_DIR/.dkcoder"
+  tools_dir="$PROJ_DIR/.dkcoder"
 fi
-#   2. Check in locations rooted under /opt/diskuv
+#   3. Check in locations rooted under /opt/diskuv
 #      We look under a /opt/diskuv early because
 #      - Especially important for WSL2 to use a pure Linux filesystem (ext4) for
 #        best performance.
@@ -507,7 +512,7 @@ if [ -z "$tools_dir" ] && [ -w "/opt/diskuv/usr/share" ]; then
   install -d "/opt/diskuv/usr/share/$tools_name"
   tools_dir="/opt/diskuv/usr/share/$tools_name"
 fi
-#   3. Check in the conventional locations rooted under /
+#   4. Check in the conventional locations rooted under /
 if [ -z "$tools_dir" ] && [ -n "${XDG_DATA_HOME:-}" ] && [ -w "$XDG_DATA_HOME" ]; then
   install -d "$XDG_DATA_HOME/$tools_name"
   tools_dir="$XDG_DATA_HOME/$tools_name"
@@ -516,9 +521,9 @@ if [ -z "$tools_dir" ] && [ -n "${HOME:-}" ] && [ -w "$HOME" ]; then
   install -d "$HOME/.local/share/$tools_name"
   tools_dir="$HOME/.local/share/$tools_name"
 fi
-#   4. Validate
+#   5. Validate
 if [ -z "$tools_dir" ]; then
-  echo "FATAL: Could not find a location to install the tools necessary for this project." >&2
+  echo "FATAL: Could not find a location to install DkCoder." >&2
   echo "  ...: Make sure you have a home directory and that it is write-able, or define" >&2
   echo "  ...: the environment variable XDG_DATA_HOME in a shell profile script after" >&2
   echo "  ...: creating the \$XDG_DATA_HOME directory." >&2
@@ -554,23 +559,23 @@ install_linux_prog() {
   else
     if [ -x /sbin/apk ]; then
       if [ "$(id -u)" -eq 0 ]; then
-        run_maybe_quiet /sbin/apk add "$install_linux_prog_ALPINE_PKG"
+        run_maybe_quiet /sbin/apk add --quiet --no-progress "$install_linux_prog_ALPINE_PKG"
       else
-        echo "Running: sudo /sbin/apk add $install_linux_prog_ALPINE_PKG"
-        sudo /sbin/apk add "$install_linux_prog_ALPINE_PKG"
+        echo "Running: sudo /sbin/apk add --quiet --no-progress  $install_linux_prog_ALPINE_PKG" >&2
+        sudo /sbin/apk add --quiet --no-progress "$install_linux_prog_ALPINE_PKG"
       fi
     elif command -v yum > /dev/null 2> /dev/null; then
       if [ "$(id -u)" -eq 0 ]; then
-        run_maybe_quiet yum install -y "$install_linux_prog_PKG"
+        run_maybe_quiet yum install -q -y "$install_linux_prog_PKG"
       else
-        echo "Running: sudo yum install -y $install_linux_prog_PKG"
-        sudo yum install -y "$install_linux_prog_PKG"
+        echo "Running: sudo yum install -q -y $install_linux_prog_PKG" >&2
+        sudo yum install -q -y "$install_linux_prog_PKG"
       fi
     else
       if [ "$(id -u)" -eq 0 ]; then
-        run_maybe_quiet apt-get -q install -y "$install_linux_prog_PKG"
+        run_maybe_quiet apt-get -qq install -y --no-install-suggests "$install_linux_prog_PKG"
       else
-        echo "Running: sudo -q apt-get -qq install -y --no-install-suggests $install_linux_prog_PKG"
+        echo "Running: sudo apt-get -qq install -y --no-install-suggests $install_linux_prog_PKG" >&2
         sudo apt-get -qq install -y --no-install-suggests "$install_linux_prog_PKG"
       fi
     fi
@@ -615,7 +620,7 @@ install_macos_prog() {
       if [ "$(id -u)" -eq 0 ]; then
         run_maybe_quiet port install "$install_macos_prog_PKG"
       else
-        echo "Running: sudo port install $install_macos_prog_PKG"
+        echo "Running: sudo port install $install_macos_prog_PKG" >&2
         sudo port install "$install_macos_prog_PKG"
       fi
       DK_PROG_INSTALLED_LOCATION=$(command -v "$install_macos_prog_NAME")
@@ -874,6 +879,14 @@ else
   dk_nonce=$$
 fi
 
+# --- Console ---
+
+if [ -t 0 ]; then
+  dk_tty=1
+else
+  dk_tty=0
+fi
+
 # --- Run finder script ---
 
 dk_work=$tools_dir/work
@@ -882,8 +895,10 @@ cd "$PROJ_DIR"
 "$cmake_bindir/cmake" \
   -D CMAKE_GENERATOR=Ninja -D CMAKE_MAKE_PROGRAM="$NINJA_EXE" \
   -D "DKCODER_PWD:FILEPATH=$dk_pwd" \
+  -D "DKCODER_DATA_HOME:FILEPATH=$tools_dir" \
   -D "DKCODER_WORKDIR:FILEPATH=$dk_work" \
   -D "DKCODER_NONCE:STRING=$dk_nonce" \
+  -D "DKCODER_TTY:STRING=$dk_tty" \
   -D "DKCODER_CMDLINE:STRING=$*" \
   -P __dk.cmake
 
